site_name: "jaysa's bloggg"
site_url: "https://blog.jaysa.net"
site_description: "jaysa's blog! :)"
theme:
  name: material 
  palette:
    primary: custom
    accent: custom
  logo: assets/logo.svg
  favicon: assets/blog-favicon.ico
  font:
    text: 'Libre Baskerville'
  features:
    - navigation.tracking
    - navigation.expand
    - navigation.footer
    - content.code.copy
extra:
  homepage: https://jaysa.net
  generator: false
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.com/users/202542121247440896
      name: 'discord: evil_girl_making_laggy_chairs'
    - icon: fontawesome/brands/signal-messenger
      link: https://signal.me/#eu/4VblAHvEA8YcdUcNxZ_x2GHjKbSdBq4dbv9_L2bUNk-BYp2WphBAJqGK0bEJiuJC
      name: 'signal: jaysa.88'
    - icon: fontawesome/solid/square-rss
      link: https://blog.jaysa.net/feed_rss_created.xml
      name: 'rss feed'
extra_css:
  - stylesheets/extra.css
  - stylesheets/extra-icons.css
  - stylesheets/gruvbox-dark.css
plugins:
  - search
  - rss:
      date_from_meta:
        as_creation: date
  - blog:
      blog_dir: .
      blog_toc: true
      archive_date_format: MMMM yyyy
      post_date_format: full
      pagination: true
      pagination_per_page: 15
      post_readtime: false
markdown_extensions:
  - attr_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: true
#  - pymdownx.emoji:
#      emoji_index: !!python/name:material.extensions.emoji.twemoji
#      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - def_list
